//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NSys2D.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_PROPSHT_CAPTION             102
#define IDC_POINTER                     104
#define IDS_PROPSHT_CAPTION1            105
#define IDD_KNOTPAGE1                   106
#define IDD_KNOTPAGE2                   107
#define IDD_KNOTPAGE3                   108
#define IDR_MAINFRAME                   128
#define IDR_NSYS2DTYPE                  129
#define IDR_SHEMETYPE                   129
#define IDR_GRAPHTYPE                   130
#define IDR_FORMSTYPE                   131
#define IDR_POPUPMENUSHEME              132
#define IDS_SIGNATURE                   132
#define IDD_DIALOGCOORD                 133
#define IDS_GROUP_SIGNATURE             133
#define IDD_DIALOGROD                   134
#define IDS_SIGNATURE_30                134
#define IDB_BITMAP_1                    135
#define IDB_BITMAP_2                    136
#define IDB_BITMAP_3                    137
#define IDB_BITMAP_1i                   138
#define IDB_BITMAP_2i                   139
#define IDB_BITMAP_3i                   140
#define IDD_DIALOGDEMF                  141
#define IDB_BITMAP_XP3                  164
#define IDB_BITMAP_XP5                  165
#define IDB_BITMAP_XP1                  166
#define IDB_BITMAP_XS1                  168
#define IDB_BITMAP_XS3                  169
#define IDB_BITMAP_XS5                  170
#define IDD_DIALOGSPRING                171
#define IDD_DIALOG1                     172
#define IDC_CURSOR1                     174
#define IDI_ICON1                       175
#define IDD_DIALOG2                     176
#define IDD_DIALOGMASS                  177
#define IDD_DIALOGELEM                  182
#define IDD_DIALOGPRECALC               186
#define IDD_DIALOGTYPEGRAPH             192
#define IDB_BITMAP_XPS                  196
#define IDB_BITMAP_XPX                  198
#define IDD_PROGRESSDIALOG              199
#define IDD_DIALOG3                     200
#define IDD_KNOTPAGE4                   200
#define IDS_EE_MISSING_CLOSE_BRACKET    201
#define IDS_EE_UNEXPECTED_SIGN          202
#define IDS_EE_UNDEFINED_ID             203
#define IDS_EE_BAD_CHAR                 204
#define IDS_EE_DIVISION_BY_ZERO         205
#define IDS_EE_UNKNOWN_FUNCTION         206
#define IDD_FREQDLG                     209
#define IDD_FREQVIEW                    212
#define IDD_KNOTPAGE5                   215
#define IDD_KNOTSPECTR                  216
#define IDD_COMPLEXSPECTR               217
#define IDD_SPECTRDLG                   219
#define IDB_BITMAP1                     222
#define IDB_BITMAP5                     223
#define IDB_BITMAP4                     224
#define IDB_BITMAP3                     225
#define IDB_BITMAP2                     226
#define IDD_DIALOG4                     228
#define IDD_FORMS_BAR                   229
#define IDD_DIALOGHARDROD               231
#define IDD_EV_METHODS                  233
#define IDD_VIEW_STYLES                 234
#define IDD_GROUP_NEW                   236
#define IDD_GROUP_LIST                  237
#define IDD_GROUP_EDIT                  238
#define IDD_DIALOG_GROUP_SHOW           239
#define IDD_DIALOG_MESH_ELEM            240
#define IDD_CONVERT_TO                  241
#define IDR_SCRIPT                      242
#define IDR_OUTPUT                      248
#define IDR_MOVIE                       251
#define IDD_MOVIE_STYLES                254
#define IDD_TIME_DLG                    255
#define IDD_SHEME_VARS                  257
#define IDD_SHEME_VAR_NEW               258
#define IDD_DESCRIPTION                 259
#define IDD_GRAPHS_PROPERTIES           260
#define IDD_GRAPH_EDIT                  261
#define IDS_GE_WRONG_SYMBOL             301
#define IDS_GE_WRONG_SYNTAX             302
#define IDS_GE_UNKNOWN                  303
#define IDS_GE_TOMANYITEMS              304
#define IDS_GE_NONAME                   305
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT5                       1005
#define IDC_EDIT6                       1006
#define IDC_EDIT7                       1007
#define IDC_EDIT8                       1008
#define IDC_EDIT9                       1009
#define IDC_EDIT10                      1010
#define IDC_EDIT11                      1011
#define IDC_EDIT12                      1012
#define IDC_EDIT13                      1013
#define IDC_EDIT14                      1014
#define IDC_EDIT15                      1015
#define IDC_CHECK1                      1021
#define IDC_CHECK2                      1022
#define IDC_CHECK3                      1023
#define IDC_CHECK4                      1024
#define IDC_COMBO1                      1031
#define IDC_COMBO2                      1032
#define IDC_COMBO3                      1033
#define IDC_COMBO4                      1034
#define IDC_RADIO1                      1041
#define IDC_RADIO2                      1042
#define IDC_RADIO3                      1043
#define IDC_RADIO4                      1044
#define IDC_RADIO5                      1045
#define IDC_RADIO6                      1046
#define IDC_RADIO7                      1047
#define IDC_RADIO8                      1048
#define IDC_RADIO9                      1049
#define IDC_RADIO10                     1050
#define IDC_RADIO11                     1051
#define IDC_RADIO12                     1052
#define IDC_RADIO13                     1053
#define IDC_RADIO14                     1054
#define IDC_RADIO15                     1055
#define IDC_RADIO16                     1056
#define IDC_LIST1                       1057
#define IDC_RADIO17                     1057
#define IDC_VARS_LIST                   1057
#define IDC_RADIO18                     1058
#define IDC_RADIO19                     1059
#define IDC_RADIO20                     1060
#define IDC_SPECTRPX                    1062
#define IDC_SPECTRPY                    1063
#define IDC_BUTTON1                     1063
#define IDC_BUTTON2                     1064
#define IDC_EDIT16                      1064
#define IDC_EDIT17                      1065
#define IDC_CSPECPY                     1065
#define IDC_EDIT18                      1066
#define IDC_MSFLEXGRID1                 1069
#define IDC_BUTNEWKNOT                  1070
#define IDC_BUTTONDEL                   1071
#define IDC_CSPECPX                     1071
#define IDC_BUTTONPROP                  1072
#define IDC_BUTTON3                     1072
#define IDC_LISTCONTROL                 1073
#define IDC_EDIT19                      1073
#define IDC_PROGRESS1                   1074
#define IDC_CSPECUX                     1075
#define IDC_CSPECUY                     1076
#define IDC_BAR_FREQ                    1077
#define IDC_BAR_T                       1078
#define IDC_TEXT_OUT                    1083
#define IDC_FREE_FONT                   1084
#define IDC_BUTTON_FREE_FONT            1085
#define IDC_CHECK_NUM_KNOTS             1086
#define IDC_CHECK_NUM_ELEMS             1087
#define IDC_NUM_KNOTS                   1088
#define IDC_BUTTON_NUM_KNOTS_FONT       1089
#define IDC_NUM_ELEMS                   1090
#define IDC_BUTTON_NUM_ELEMS_FONT       1091
#define IDC_RADIO_HARDMETHOD_0          1092
#define IDC_RADIO_HARDMETHOD_1          1093
#define IDC_RADIO_HARDMETHOD_2          1094
#define IDC_CHECK_CONDMASS              1095
#define IDC_EDIT_GROUP_NAME             1096
#define IDC_RADIO_GROUP_TYPE            1097
#define IDC_RADIO_GROUP_TYPE2           1098
#define IDC_EDIT_GROUP                  1099
#define IDC_GRLIST                      1100
#define IDC_BUTTON_DEL_GROUP            1101
#define IDC_BUTTON_EDIT_GROUP           1102
#define IDC_BUTTON_GROUP_SHOW           1103
#define IDC_EDIT_GROUP_NAME_INEDIT      1104
#define IDC_EDIT_GROUP_TYPE_INEDIT      1105
#define IDC_EDIT_GROUP_INEDIT           1106
#define IDC_EDIT_GROUP_SET              1107
#define IDC_BUTTON_REFRESH              1108
#define IDC_BUTTON_GROUP_SHOW_INEDIT    1109
#define IDC_EDIT_ELEMS_COUNT            1110
#define IDC_BUTTON_PACK                 1111
#define IDC_EDIT_NEW_ELEM_TYPE          1112
#define IDC_EDIT_LEFT_KNOT              1113
#define IDC_EDIT_RIGHT_KNOT             1114
#define IDC_EDIT_LEFT_PROC              1115
#define IDC_EDIT_RIGHT_PROC             1116
#define IDC_SLIDER1                     1117
#define IDC_EDIT_LEFT_LENGTH            1118
#define IDC_EDIT_RIGHT_LENGTH           1119
#define IDC_EDIT_LENGTH                 1120
#define IDC_BUTTON_GROUP_OPEN           1121
#define IDC_BUTTON_GROUP_SAVE           1122
#define IDC_EDIT_ZERO_ROT               1123
#define IDC_EDIT_TIMER_ELAPSE           1124
#define IDC_EDIT_START_TIME             1125
#define IDC_CHECK_SHOW_KNOTS            1127
#define IDC_CHECK_INTEGR_TEST           1128
#define IDC_ADD_VAR                     1129
#define IDC_RECALC                      1130
#define IDC_EDIT_VAR                    1131
#define IDC_EDIT_NAME                   1132
#define IDC_EDIT_EXPR                   1133
#define IDC_DEL_VAR                     1134
#define IDC_EDIT_DESCRIPTION            1135
#define IDC_RADIO_INVERT_0              1136
#define IDC_RADIO_INVERT_1              1137
#define IDC_CHECK_VALIDATE_EXPR         1138
#define IDC_GRAPH_LIST                  1144
#define IDC_GRAPH_EDIT                  1145
#define IDC_GRAPH_NEW                   1146
#define IDC_CAPTION                     1147
#define IDC_GRAPH_FILE_NAME             1148
#define IDC_EDIT_GRAPH_COLOR            1150
#define IDC_GRAPH_LOAD                  1151
#define IDC_GRAPH_SCALE                 1152
#define IDC_GRAPH_COLOR                 1153
#define IDC_GRAPH_DEL                   1154
#define IDC_DETAILS                     1155
#define IDC_RICH_CALC                   1156
#define IDC_RADIO_JACOBY                1179
#define IDC_RADIO_QR_ELM                1180
#define IDC_RADIO_QR_DIR                1181
#define IDC_RADIO_QR_ORT                1182
#define IDC_ROD                         2001
#define IDC_SPRING                      2002
#define IDC_DEMF                        2003
#define IDC_MASS                        2004
#define IDC_NULL                        2005
#define IDC_HARDROD                     2006
#define ID_ADDGRAPH                     32773
#define ID_ADDROD                       32774
#define ID_SPECTR_CALC                  32775
#define ID_BUTMOVE                      32777
#define ID_BUTDRAWROD                   32778
#define ID_BUTINF                       32780
#define ID_SETSPRING                    32781
#define ID_SETDEMF                      32782
#define ID_SCALEADD                     32783
#define ID_SCALESUB                     32784
#define ID_SETROD                       32785
#define ID_ADDDEMF                      32786
#define ID_ADDSPRING                    32787
#define ID_SETMASS                      32791
#define ID_ADDMASS                      32792
#define ID_LISTELEM                     32793
#define ID_CALC                         32794
#define ID_HORSUB                       32795
#define ID_VERTSUB                      32796
#define ID_DELELEM                      32797
#define ID_TEST                         32798
#define ID_HORADD                       32800
#define ID_VERTADD                      32802
#define ID_SETNULL                      32804
#define ID_AUTOSIZE                     32805
#define ID_PROP                         32806
#define ID_SAVEREZ                      32808
#define ID_REFRESH                      32809
#define ID_GETCOORD                     32810
#define ID_FREQ_CALC                    32811
#define ID_FREEFORM_CALC                32813
#define ID_MOVEADD                      32814
#define ID_MOVESUB                      32815
#define ID_FREQPREW                     32816
#define ID_FREQNEXT                     32817
#define ID_ANGLSUB                      32819
#define ID_LOADGRAPH2                   32820
#define ID_GRAPH2                       32821
#define ID_SPECTR                       32823
#define ID_UPDATEFORMS                  32828
#define ID_CALCMAT                      32829
#define ID_CALCDISP                     32830
#define ID_SETHARDROD                   32832
#define ID_ADDHARDROD                   32833
#define ID_SHEME_PARAMS                 32834
#define ID_VIEW_STYLES                  32835
#define ID_GROUP_LIST                   32836
#define ID_GROUP_NEW                    32837
#define ID_ELEMGROUP_DEL                32838
#define ID_ELEMGROUP_PROP               32839
#define ID_GROUP_PREVIEW                32840
#define ID_MESH_ELEM                    32841
#define ID_BUTTON_AUTO_SIZE             32842
#define ID_AUTO_SCALE                   32843
#define ID_CONVERT_TO                   32844
#define ID_ALL_RODS                     32845
#define ID_ALL_HARDRODS                 32846
#define ID_ALL_DEMF                     32847
#define ID_ALL_SPRINGS                  32848
#define ID_ALL_MASSES                   32849
#define ID_GROUP_CONVERT_TO             32850
#define ID_GROUP_CLICK_ELEMS            32851
#define ID_GROUP_CLICK_KNOTS            32852
#define ID_BUTTON_GRCLICK_ELEMS         32854
#define ID_BUTTON_GRCLICK_KNOTS         32855
#define ID_BUTTON_DEL_FREE_KNOTS        32856
#define ID_AUTOCORRECT                  32857
#define ID_OPEN_SCRIPT                  32858
#define ID_COMPILE_SCRIPT               32862
#define ID_RUN_SCRIPT                   32863
#define ID_SCRIPT_FILE_NEW              32864
#define ID_SCRIPT_FILE_OPEN             32865
#define ID_SCRIPT_FILE_SAVE             32866
#define ID_SCRIPT_FILE_SAVE_AS          32867
#define ID_OUTPUT_FILE_SAVE             32869
#define ID_OUTPUT_BREAK                 32870
#define ID_FREE_NUMS                    32872
#define ID_SCRIPT_CLOSE_VIEW            32873
#define ID_ACCEL32874                   32874
#define ID_MOVIE                        32875
#define ID_MOVIE_RUN                    32875
#define ID_MAKE_MOVIE                   32876
#define ID_MOVIE_STOP                   32877
#define ID_MOVIE_PARAMS                 32881
#define ID_MOVIE_SCALE_INC              32882
#define ID_MOVIE_SCALE_DEC              32883
#define ID_MOVIE_NEXT_STEP              32884
#define ID_MOVIE_PREV_STEP              32885
#define ID_MOVIE_MOVE_RIGHT             32886
#define ID_MOVIE_MOVE_LEFT              32887
#define ID_MOVIE_AUTO_SCALE             32888
#define ID_MOVIE_MOVE_UP                32889
#define ID_MOVIE_MOVE_DOWN              32890
#define ID_MOVIE_PAUSE                  32891
#define ID_TEMP                         32892
#define ID_CURRENT_TIME                 10000
//#define ID_CURRENT_TIME                 32893
#define ID_SHEME_VARS                   32893
#define ID_DESCRIPT                     32894
#define ID_GRAPH_PROP                   32895
#define ID_MAIN_GRAPH                   32896
#define ID_TOOL_TIPS                    32897

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         32898
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
