//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NSys2D.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_PROPSHT_CAPTION             102
#define IDC_POINTER                     104
#define IDS_PROPSHT_CAPTION1            105
#define IDD_KNOTPAGE1                   106
#define IDD_KNOTPAGE2                   107
#define IDD_KNOTPAGE3                   108
#define IDR_MAINFRAME                   128
#define IDR_NSYS2DTYPE                  129
#define IDR_SHEMETYPE                   129
#define IDR_GRAPHTYPE                   130
#define IDR_FORMSTYPE                   131
#define IDR_POPUPMENUSHEME              132
#define IDD_DIALOGCOORD                 133
#define IDD_DIALOGROD                   134
#define IDB_BITMAP_1                    135
#define IDB_BITMAP_2                    136
#define IDB_BITMAP_3                    137
#define IDB_BITMAP_1i                   138
#define IDB_BITMAP_2i                   139
#define IDB_BITMAP_3i                   140
#define IDD_DIALOGDEMF                  141
#define IDB_BITMAP_XP3                  164
#define IDB_BITMAP_XP5                  165
#define IDB_BITMAP_XP1                  166
#define IDB_BITMAP_XS1                  168
#define IDB_BITMAP_XS3                  169
#define IDB_BITMAP_XS5                  170
#define IDD_DIALOGSPRING                171
#define IDD_DIALOG1                     172
#define IDC_CURSOR1                     174
#define IDI_ICON1                       175
#define IDD_DIALOG2                     176
#define IDD_DIALOGMASS                  177
#define IDD_DIALOGELEM                  182
#define IDD_DIALOGPRECALC               186
#define IDD_DIALOGTYPEGRAPH             192
#define IDB_BITMAP_XPS                  196
#define IDB_BITMAP_XPX                  198
#define IDD_PROGRESSDIALOG              199
#define IDD_DIALOG3                     200
#define IDD_KNOTPAGE4                   200
#define IDS_EE_MISSING_CLOSE_BRACKET    201
#define IDS_EE_UNEXPECTED_SIGN          202
#define IDS_EE_UNDEFINED_ID             203
#define IDS_EE_BAD_CHAR                 204
#define IDS_EE_DIVISION_BY_ZERO         205
#define IDS_EE_UNKNOWN_FUNCTION         206
#define IDD_FREQDLG                     209
#define IDD_FREQVIEW                    212
#define IDD_KNOTPAGE5                   215
#define IDD_KNOTSPECTR                  216
#define IDD_COMPLEXSPECTR               217
#define IDD_SPECTRDLG                   219
#define IDB_BITMAP1                     222
#define IDB_BITMAP5                     223
#define IDB_BITMAP4                     224
#define IDB_BITMAP3                     225
#define IDB_BITMAP2                     226
#define IDD_DIALOG4                     228
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT5                       1005
#define IDC_EDIT6                       1006
#define IDC_EDIT7                       1007
#define IDC_EDIT8                       1008
#define IDC_EDIT9                       1009
#define IDC_EDIT10                      1010
#define IDC_EDIT11                      1011
#define IDC_EDIT12                      1012
#define IDC_EDIT13                      1013
#define IDC_EDIT14                      1014
#define IDC_EDIT15                      1015
#define IDC_CHECK1                      1021
#define IDC_CHECK2                      1022
#define IDC_CHECK3                      1023
#define IDC_CHECK4                      1024
#define IDC_COMBO1                      1031
#define IDC_COMBO2                      1032
#define IDC_COMBO3                      1033
#define IDC_COMBO4                      1034
#define IDC_RADIO1                      1041
#define IDC_RADIO2                      1042
#define IDC_RADIO3                      1043
#define IDC_RADIO4                      1044
#define IDC_RADIO5                      1045
#define IDC_RADIO6                      1046
#define IDC_RADIO7                      1047
#define IDC_RADIO8                      1048
#define IDC_RADIO9                      1049
#define IDC_RADIO10                     1050
#define IDC_RADIO11                     1051
#define IDC_RADIO12                     1052
#define IDC_RADIO13                     1053
#define IDC_RADIO14                     1054
#define IDC_RADIO15                     1055
#define IDC_RADIO16                     1056
#define IDC_LIST1                       1057
#define IDC_RADIO17                     1057
#define IDC_RADIO18                     1058
#define IDC_RADIO19                     1059
#define IDC_RADIO20                     1060
#define IDC_SPECTRPX                    1062
#define IDC_SPECTRPY                    1063
#define IDC_BUTTON1                     1063
#define IDC_BUTTON2                     1064
#define IDC_EDIT16                      1064
#define IDC_EDIT17                      1065
#define IDC_CSPECPY                     1065
#define IDC_EDIT18                      1066
#define IDC_MSFLEXGRID1                 1069
#define IDC_BUTNEWKNOT                  1070
#define IDC_BUTTONDEL                   1071
#define IDC_CSPECPX                     1071
#define IDC_BUTTONPROP                  1072
#define IDC_BUTTON3                     1072
#define IDC_LISTCONTROL                 1073
#define IDC_EDIT19                      1073
#define IDC_PROGRESS1                   1074
#define IDC_CSPECUX                     1075
#define IDC_CSPECUY                     1076
#define IDC_ROD                         2001
#define IDC_SPRING                      2002
#define IDC_DEMF                        2003
#define IDC_MASS                        2004
#define IDC_NULL                        2005
#define ID_ADDGRAPH                     32773
#define ID_ADDROD                       32774
#define ID_SPECTR_CALC                  32775
#define ID_BUTMOVE                      32777
#define ID_BUTDRAWROD                   32778
#define ID_BUTINF                       32780
#define ID_SETSPRING                    32781
#define ID_SETDEMF                      32782
#define ID_SCALEADD                     32783
#define ID_SCALESUB                     32784
#define ID_SETROD                       32785
#define ID_ADDDEMF                      32786
#define ID_ADDSPRING                    32787
#define ID_SETMASS                      32791
#define ID_ADDMASS                      32792
#define ID_LISTELEM                     32793
#define ID_CALC                         32794
#define ID_HORSUB                       32795
#define ID_VERTSUB                      32796
#define ID_DELELEM                      32797
#define ID_TEST                         32798
#define ID_HORADD                       32800
#define ID_VERTADD                      32802
#define ID_SETNULL                      32804
#define ID_AUTOSIZE                     32805
#define ID_PROP                         32806
#define ID_SAVEREZ                      32808
#define ID_REFRESH                      32809
#define ID_GETCOORD                     32810
#define ID_FREQ_CALC                    32811
#define ID_FREEFORM_CALC                32813
#define ID_MOVEADD                      32814
#define ID_MOVESUB                      32815
#define ID_FREQPREW                     32816
#define ID_FREQNEXT                     32817
#define ID_ANGLSUB                      32819
#define ID_LOADGRAPH2                   32820
#define ID_GRAPH2                       32821
#define ID_SPECTR                       32823
#define ID_UPDATEFORMS                  32828
#define ID_CALCMAT                      32829
#define ID_CALCDISP                     32830

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        229
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
